-------------------
--FINALIDADE-------
-------------------
INSERT INTO FINALIDADE (ID, FINALIDADE) VALUES(1	, HIPERTROFIA);
INSERT INTO FINALIDADE (ID, FINALIDADE) VALUES(2	, FORTALECIMENTO MUSCULAR);
INSERT INTO FINALIDADE (ID, FINALIDADE) VALUES(3	, RESISTENCIA MUSCULAR);
INSERT INTO FINALIDADE (ID, FINALIDADE) VALUES(4	, PERDA DE PESO);

-------------------
--MUSCULO-------
-------------------
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(1		, ABDMEN);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(2		, AERÓBICO);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(3		, BICEPS);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(4		, COSTAS);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(5		, COXAS);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(6		, GLUTEOS);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(7		, OMBRO);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(8		, PANTURRILHA);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(9		, PEITO);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(10	, QUADRIL);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(11	, TRICEPS);
INSERT INTO MUSCULO (ID, NOME_MUSCULO) VALUES(12	, TRAPÉZIO);




